import React from "react";
import { 
  LineChart, 
  Line, 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  ResponsiveContainer, 
  Legend 
} from "recharts";
import { LineChart as ChartIcon, BarChart2, Compass, AlertTriangle, Droplets } from "lucide-react";

export default function Analytics({ data }) {
  if (!data) return <div className="text-gray-400 p-8 text-center">Reading forecast indicators...</div>;

  // Prepare data for Traffic Congestion forecast
  // We'll take Zone 5 (CBD) predictions as representative
  const zone5Traffic = data.predictions["zone_5"]?.traffic || [];
  const trafficChartData = zone5Traffic.map((item) => ({
    time: `+${item.time_offset_hours} hrs (Hour ${item.hour_of_day}:00)`,
    Congestion: item.predicted_score,
  }));

  // Prepare data for AQI Day predictions
  const zone5Aqi = data.predictions["zone_5"]?.aqi_forecast || [];
  const aqiChartData = zone5Aqi.map((item) => ({
    name: item.day,
    AQI: item.aqi,
  }));

  // Prepare data comparing Flood Risk percentage by zones
  const floodRiskData = data.sensor_data.map((zone) => ({
    name: zone.name.split(" ")[0], // Just get direction (e.g. North, East)
    "Flood Risk %": data.predictions[zone.id]?.flood?.risk_score || 0,
    "Rainfall (mm)": zone.weather.precipitation_mm,
  }));

  return (
    <div className="space-y-6">
      <div>
        <h2 className="font-header font-extrabold text-3xl text-white">Community Risk Forecast Center</h2>
        <p className="text-gray-400 text-sm mt-1">Multi-hour predictive modeling outputs generated by local risk neural nets.</p>
      </div>

      <div className="grid grid-cols-12 gap-6">
        {/* Chart 1: Flood Risk by Zone */}
        <div className="col-span-12 glass-panel rounded-2xl p-6">
          <h3 className="font-header font-bold text-lg text-gray-200 mb-6 flex items-center gap-2">
            <Droplets size={18} className="text-blue-400" />
            Active Flood Risk Comparison by Zone
          </h3>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={floodRiskData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="name" stroke="#9ca3af" fontSize={11} />
                <YAxis stroke="#9ca3af" fontSize={11} />
                <Tooltip 
                  contentStyle={{ background: "#111827", borderColor: "rgba(255,255,255,0.1)", color: "#fff" }} 
                  itemStyle={{ fontSize: 12 }}
                />
                <Legend />
                <Bar dataKey="Flood Risk %" fill="#3b82f6" radius={[4, 4, 0, 0]} />
                <Bar dataKey="Rainfall (mm)" fill="#10b981" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 2: 24h Traffic Congestion Prediction */}
        <div className="col-span-12 md:col-span-6 glass-panel rounded-2xl p-6">
          <h3 className="font-header font-bold text-lg text-gray-200 mb-6 flex items-center gap-2">
            <Compass size={18} className="text-indigo-400" />
            24h Traffic Congestion Outlook (Central District)
          </h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trafficChartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="time" stroke="#9ca3af" fontSize={10} />
                <YAxis stroke="#9ca3af" fontSize={10} />
                <Tooltip 
                  contentStyle={{ background: "#111827", borderColor: "rgba(255,255,255,0.1)", color: "#fff" }}
                />
                <Line type="monotone" dataKey="Congestion" stroke="#f59e0b" strokeWidth={3} activeDot={{ r: 8 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 3: 3-Day AQI Index Trend */}
        <div className="col-span-12 md:col-span-6 glass-panel rounded-2xl p-6">
          <h3 className="font-header font-bold text-lg text-gray-200 mb-6 flex items-center gap-2">
            <BarChart2 size={18} className="text-emerald-400" />
            3-Day AQI Trend Outlook (Particulate Dispersion)
          </h3>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={aqiChartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="name" stroke="#9ca3af" fontSize={11} />
                <YAxis stroke="#9ca3af" fontSize={11} />
                <Tooltip 
                  contentStyle={{ background: "#111827", borderColor: "rgba(255,255,255,0.1)", color: "#fff" }}
                />
                <Bar dataKey="AQI" fill="#10b981" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
}
